### ISSUE TITLE
Can you please tell my what may be causing this error? (Log)

### ISSUE THREAD

**Issue by lacedup** [jeroenterheerdt/ring-hassio#17]
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
output directory: public/
Started server, listening on port 3720.
Call has ended
Server closed!
/ring-hassio/ring_hassio/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
    at Object.unlinkSync (fs.js:1126:10)
    at SafeSubscriber._next (/ring-hassio/ring_hassio/livestream.js:202:28)
    at SafeSubscriber.__tryOrUnsub (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ReplaySubject.Subject.next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (/ring-hassio/ring_hassio/node_modules/rxjs/internal/ReplaySubject.js:48:31)
    at SipSession.callEnded (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip-session.js:176:33)
    at SafeSubscriber._next (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip-session.js:149:35) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[cmd] /ring-hassio/ring_hassio/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal. `

Thank you

**Comment by cmatte** [comment]
Same error here, after a first positive live streaming seen working, and an HA reboot, this occurred.

Attempted to uninstall and re-install, did not work.

Full log:
`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
output directory: public/
Started server, listening on port 3000.
Call has ended
Server closed!
/ring-hassio/ring_hassio/node_modules/rxjs/internal/util/hostReportError.js:4
    setTimeout(function () { throw err; }, 0);
                             ^
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Object
    at Object.unlinkSync (fs.js:1126:10)
    at SafeSubscriber._next (/ring-hassio/ring_hassio/livestream.js:202:28)
    at SafeSubscriber.__tryOrUnsub (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:143:22)
    at Subscriber._next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subscriber.js:66:18)
    at ReplaySubject.Subject.next (/ring-hassio/ring_hassio/node_modules/rxjs/internal/Subject.js:60:25)
    at ReplaySubject.nextInfiniteTimeWindow (/ring-hassio/ring_hassio/node_modules/rxjs/internal/ReplaySubject.js:48:31)
    at SipSession.callEnded (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip-session.js:176:33)
    at SafeSubscriber._next (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip-session.js:149:35) {
  code: 'ERR_INVALID_ARG_TYPE'
}
[cmd] /ring-hassio/ring_hassio/run.sh exited 1
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.`


Supervisor log:
`20-07-11 01:18:21 INFO (MainThread) [supervisor.homeassistant] Detect a running Home Assistant instance
20-07-11 01:18:56 INFO (SyncWorker_5) [supervisor.docker.interface] Clean addon_44c60309_ringlivestream application
20-07-11 01:19:01 INFO (SyncWorker_5) [supervisor.docker.addon] Start Docker add-on 44c60309/amd64-addon-ringlivestream with version 1.1
20-07-11 01:21:00 INFO (SyncWorker_15) [supervisor.docker.interface] Clean addon_44c60309_ringlivestream application
20-07-11 01:21:07 INFO (SyncWorker_15) [supervisor.docker.addon] Start Docker add-on 44c60309/amd64-addon-ringlivestream with version 1.1
20-07-11 01:23:39 INFO (SyncWorker_9) [supervisor.docker.interface] Clean addon_44c60309_ringlivestream application
20-07-11 01:23:48 INFO (SyncWorker_9) [supervisor.docker.addon] Start Docker add-on 44c60309/amd64-addon-ringlivestream with version 1.1
20-07-11 01:25:43 INFO (SyncWorker_13) [supervisor.docker.interface] Clean addon_44c60309_ringlivestream application
20-07-11 01:25:44 INFO (SyncWorker_13) [supervisor.docker.interface] Remove image 44c60309/amd64-addon-ringlivestream with latest and 1.1
20-07-11 01:25:46 INFO (MainThread) [supervisor.addons.addon] Remove add-on data folder /data/addons/data/44c60309_ringlivestream
20-07-11 01:25:46 INFO (MainThread) [supervisor.addons] Add-on '44c60309_ringlivestream' successfully removed
20-07-11 01:26:06 INFO (MainThread) [supervisor.addons] Create Home Assistant add-on data folder /data/addons/data/44c60309_ringlivestream
20-07-11 01:26:06 INFO (SyncWorker_6) [supervisor.docker.addon] Start build 44c60309/amd64-addon-ringlivestream:1.1
20-07-11 01:26:08 INFO (SyncWorker_6) [supervisor.docker.addon] Build 44c60309/amd64-addon-ringlivestream:1.1 done
20-07-11 01:26:08 INFO (MainThread) [supervisor.addons] Add-on '44c60309_ringlivestream' successfully installed
20-07-11 01:26:33 INFO (SyncWorker_2) [supervisor.docker.addon] Start Docker add-on 44c60309/amd64-addon-ringlivestream with version 1.1`

**Comment by jeroenterheerdt** [comment]
sorry, I don't know what is going on here. There is something going on in the underlying node.js code. Check here to see if there is anything that might be wrong:https://github.com/dgreif/ring

**Comment by jeroenterheerdt** [comment]
should be fixed now,
