### ISSUE TITLE
Works for 10-15 seconds

### ISSUE THREAD

**Issue by petarvucetin** [jeroenterheerdt/ring-hassio#31]
Watching it in VLC works for 15 seconds than I get:
socket 1 closed
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/ring-hassio/ring_hassio/node_modules/sip/sip.js:584:43)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/ring-hassio/ring_hassio/node_modules/sip/sip.js:584:43)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/ring-hassio/ring_hassio/node_modules/sip/sip.js:584:43)
    at TLSSocket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Call has ended

Any ideas?

**Comment by Patrick1610** [comment]
Have you found a solution?

**Comment by petarvucetin** [comment]
Nope.
