### ISSUE TITLE
Cannot read property 'streamVideo' of undefined     at /ring-hassio/ring_hassio/livestream.js:194:53

### ISSUE THREAD

**Issue by mghome59** [jeroenterheerdt/ring-hassio#34]
Hi , I ended up with this error : 

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Checking If Ingresso principale Is the same as the camera we are looking for (Front Door)
output directory: public/
Started server, listening on port 3000.
(node:198) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'streamVideo' of undefined
    at /ring-hassio/ring_hassio/livestream.js:194:53
    at step (/ring-hassio/ring_hassio/livestream.js:34:23)
    at Object.next (/ring-hassio/ring_hassio/livestream.js:15:53)
    at fulfilled (/ring-hassio/ring_hassio/livestream.js:6:58)
(node:198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
socket 0 opened
socket 0 closed
socket 1 opened
socket 2 opened
requested uri: /
requested uri: /public/stream.m3u8
mapped filename: public/stream.m3u8
file not found: public/stream.m3u8
socket 2 closed
socket 1 closed
socket 3 opened
socket 4 opened
requested uri: /index.html
requested uri: /public/stream.m3u8
mapped filename: public/stream.m3u8
file not found: public/stream.m3u8
socket 4 closed
socket 3 closed
socket 5 opened
socket 6 opened
requested uri: /public/stream.m3u8
mapped filename: public/stream.m3u8
file not found: public/stream.m3u8
socket 6 closed
socket 5 closed 

Can you please help me ?

**Comment by merlin2k** [comment]
Same problem here

**Comment by Micha7719** [comment]
Hello, found the problem. You have to set the name of the ring correctly in the configuration.
In your case, the configuration should say "Front Door".
If you enter another name it will not find the cam and no stream is available.

"Checking If Ingresso principale Is the same as the camera we are looking for (**Front Door)**"

Also i use in Camsettings:
platform: ffmpeg
  input: http://IP-Adress:3000/public/stream.m3u8
  name: Front Door

I had to use the IP address instead of the host that it worked
Hope I could help, please let me know

**Comment by DeliriousMetro** [comment]
> Hello, found the problem. You have to set the name of the ring correctly in the configuration.
> In your case, the configuration should say "Front Door".
> If you enter another name it will not find the cam and no stream is available.
> 
> "Checking If Ingresso principale Is the same as the camera we are looking for (**Front Door)**"
> 
> Also i use in Camsettings:
> platform: ffmpeg
> input: http://IP-Adress:3000/public/stream.m3u8
> name: Front Door
> 
> I had to use the IP address instead of the host that it worked
> Hope I could help, please let me know

Yep, can confirm - that is how I have had mine set-up for months.

It is in the readme.md
> The camera name is the name entred when setting up the camera in the Ring app.

**Comment by mghome59** [comment]
I confirm that was the problem . Thanks you all !!!
