### ISSUE TITLE
Worked 1 day 

### ISSUE THREAD

**Issue by johanvh83** [jeroenterheerdt/ring-hassio#37]
Hi,
Yesterday I was able to start and stop the add-on and after a start I received livestreams.
After start of the add-on today I got below log:

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Checking If Voordeur Is the same as the camera we are looking for (Voordeur)
Matched Voordeur
output directory: public/
Started server, listening on port 3000.
Call has ended
Restarting server
Server closed!
(node:198) UnhandledPromiseRejectionWarning: Error: SIP request made after call was destroyed
    at SipCall.request (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip-call.js:117:35)
    at SipCall.sendKeyFrameRequest (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip-call.js:188:21)
    at SipCall.<anonymous> (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip-call.js:216:24)
    at Generator.next (<anonymous>)
    at fulfilled (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip-call.js:5:58)
(node:198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Checking If Voordeur Is the same as the camera we are looking for (Voordeur)
Matched Voordeur
output directory: public/
Started server, listening on port 3000.

Restarted Home Assistant, tried again and it worked for 1 time (below normal log in working order).
What could be the reason of the above behaviour, and more important, could it be resolved?

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Checking If Voordeur Is the same as the camera we are looking for (Voordeur)
Matched Voordeur
output directory: public/
Started server, listening on port 3000.
socket 0 opened
requested uri: /public/stream.m3u8
mapped filename: public/stream.m3u8
sending file: public/stream.m3u8
socket 1 opened
socket 0 closed
requested uri: /public/stream19.ts
mapped filename: public/stream19.ts
sending file: public/stream19.ts
socket 2 opened
requested uri: /public/stream20
And so on....

**Comment by Patrick1610** [comment]
Have you found a solution? Mine does the same and fills my history with live view

**Comment by ZoltXs** [comment]
Have you found a solution?
