### ISSUE TITLE
UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by tderoy** [jeroenterheerdt/ring-hassio#52]
Hello there,

First of all, thank you for this amazing add-on :)
It is one of the reason I moved my HomeAssistant configuration from Docker to a VM so I can use it.

It was working perfectly until the beginning of this week, the add-on doesn't start anymore and I have the following message inside the logs:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
(node:198) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at Request.<anonymous> (/ring-hassio/ring_hassio/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[cmd] /ring-hassio/ring_hassio/run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
```

I tried the following actions but it still not working:

- re-install the add-on (Current version: 1.35)
- generate a new token
- make sure that the device name match the one defined in Ring Application.

Any idea where the issue might come from?

Thanks in advanced for your answer,

Tom

**Comment by clartan2014** [comment]
got the same issue and tried reinstalling and regenerating token too but no luck.

**Comment by richardhopton** [comment]
I've pushed a pull request to fix this - and can confirm that it works now with no error based on my master branch.
