### ISSUE TITLE
file not found - No stream

### ISSUE THREAD

**Issue by dping28** [jeroenterheerdt/ring-hassio#60]
I have an unraid server with a Hassio VM. I installed ring-hassio in Supervisor Add-ons and configured it with a Refresh Token and I start it. All seems well except there is no stream in Web or in VLC. If i go to the /public/stream.m3u8 url I only see:

file not found: %s

Log only shows:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Checking If Ring Cam Is the same as the camera we are looking for (Ring Cam)
Matched Ring Cam
output directory: public/
Started server, listening on port 3000.
socket 0 opened
requested uri: /index.html
requested uri: /favicon.ico
mapped filename: favicon.ico
file not found: favicon.ico
socket 0 closed
socket 1 opened
requested uri: /public/stream.m3u8
mapped filename: public/stream.m3u8
sending file: public/stream.m3u8
requested uri: /public/stream.m3u8
mapped filename: public/stream.m3u8
sending file: public/stream.m3u8
socket 1 closed
err:  Error: remote peer disconnected
    at TLSSocket.<anonymous> (/ring-hassio/ring_hassio/node_modules/ring-client-api/lib/api/sip.js:557:38)
    at TLSSocket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Call has ended
Restarting server
Server closed!
Checking If Ring Cam Is the same as the camera we are looking for (Ring Cam)`

It repeats continuously from "Checking if..." all the way down to the err. If it matters I can load the camera in the ring app. I also did try removing and re-adding ring-hassio. Very new to HA so probably something I did :)

**Comment by dping28** [comment]
If it helps - When I start the service in HA I do see the blue status LED come on on the camera. It goes off when i stop the service too. Just no file to access the stream.
