### ISSUE TITLE
addon dont work 

### ISSUE THREAD

**Issue by Benoulimou** [jeroenterheerdt/ring-hassio#69]
Hello, 

Thank you for this addon. 
I have installed the token but I have this error and I can't access the cameras.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
(node:198) UnhandledPromiseRejectionWarning: HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/ring-hassio/ring_hassio/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[cmd] /ring-hassio/ring_hassio/run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.`

Can you help me?

**Comment by CAVACO-PT** [comment]
same here  :

[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] done.
[services.d] starting services
[services.d] done.
(node:198) UnhandledPromiseRejectionWarning: HTTPError: Response code 500 (Internal Server Error)
    at Request.<anonymous> (/ring-hassio/ring_hassio/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[cmd] /ring-hassio/ring_hassio/run.sh exited 0
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.

**Comment by CAVACO-PT** [comment]
It was a global outage on amazon , its working again for me !!!

**Comment by Benoulimou** [comment]
not for me

**Comment by Benoulimou** [comment]
`Checking If Devant Is the same as the camera we are looking for (Front Door)
Checking If Portail Entrée  Is the same as the camera we are looking for (Front Door)
Checking If Porte d'entrée Is the same as the camera we are looking for (Front Door)
output directory: public/
Started server, listening on port 3000.
(node:198) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'streamVideo' of undefined
    at /ring-hassio/ring_hassio/livestream.js:194:53
    at step (/ring-hassio/ring_hassio/livestream.js:34:23)
    at Object.next (/ring-hassio/ring_hassio/livestream.js:15:53)
    at fulfilled (/ring-hassio/ring_hassio/livestream.js:6:58)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:198) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:198) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`
